import type { Metadata } from 'next'

import React from 'react'

import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const features = [
  'Auth',
  'Create_Publication',
  'Favorites',
  'Feed',
  'Messenger',
  'Post',
  'Profile',
  'Profile_Settings',
  'Search',
  'Statistics',
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{ display: 'flex', gap: '30px', padding: '30px' }}>
          {features.map(feature => (
            <Link key={feature} href={`/${feature.toLowerCase()}`}>
              <h3>{feature}</h3>
            </Link>
          ))}
        </header>
        {children}
      </body>
    </html>
  )
}
